### ISSUE TITLE
[BUG] tinynodes/ngx-editorjs@3.1.0 : Cannot get the editor content

### ISSUE THREAD

**Issue by bballay-cendryon** [tanepiper/ngx-tinynodes#21]
**Which Library?**
tinynodes/ngx-editorjs

**Describe the bug**
When using the NgxEditorJSComponentModule, the blocks value is not updating. Issue also occurs on the demo website

**To Reproduce**
Check out the sample firebase app

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Comment by tanepiper** [comment]
@bballay-futeq Hi, I've fixed this in 4.0.0 release

**Comment by tanepiper** [comment]
@bballay-futeq Closing this ticket as no reply, hopefully you can use release 4 to fix this
