### ISSUE TITLE
[BUG] <ngx-editorJS - 4.0.0>: TypeError: this.editorJs is not a constructor 

### ISSUE THREAD

**Issue by CarlosValencia78** [tanepiper/ngx-tinynodes#24]
**Which Library?**
ngx-editorjs

**Describe the bug**
Attempting to setup ngx-editorjs in Angular 9 project, but receive the error:

TypeError: this.editorJs is not a constructor
        at NgxEditorJSService.<anonymous> (tinynodes-ngx-editorjs.js:163)
        ...
        ...

**To Reproduce**
1. Install ngx-editorjs (npm install @tinynode/ngx-editorjs) and ALL dependencies

2. In package.json:

"@editorjs/code": "^2.6.0",
"@editorjs/editorjs": "^2.19.0",
"@editorjs/embed": "^2.4.0",
"@editorjs/header": "^2.6.1",
"@editorjs/image": "^2.6.0",
"@editorjs/inline-code": "^1.3.1",
"@editorjs/link": "^2.3.1",
"@editorjs/list": "^1.6.1",
"@editorjs/paragraph": "^2.8.0",
"@editorjs/quote": "^2.4.0",
"@editorjs/simple-image": "^1.4.0",
"@editorjs/warning": "^1.2.0",
"@tinynodes/ngx-editorjs": "^4.0.0",
"@tinynodes/ngx-editorjs-plugins": "^3.0.0"

3. In app.module.ts

import { NgxEditorJSComponentModule } from '@tinynodes/ngx-editorjs"
import { NgxEditorjsPluginsModule } from '@tinynodes/ngx-editorjs-plugins"
....
@NgModule({
...
imports:[
...
NgxEditorJSComponentModule,
NgxEditorjsPluginsModule 
]
...
})

4. instance in my components html (inputs.component.html):

<ngx-editorjs [holder]="'editorJS'"></ngx-editorjs>

**Expected behavior**
Expect to see the editor.js component / editor

**Screenshots**
No screenshots as this is a task for my job and I am using my personal computer to post this message.

**Desktop (please complete the following information):**
Chrome

**Comment by tanepiper** [comment]
Cannot reproduce, working example here https://github.com/tanepiper/basic-editorjs-example

**Comment by CarlosValencia78** [comment]
I cloned your example and it is working fine.

However, I have copied what you have in package.json, app.component.html and app.module.ts and am now faced with new erros:

ERROR error: Uncaught (in promise) Error: Error in NgxEditorJSDirective::ngAfterContentInit - Directive element has no ID

When I update the ngx-editorjs tag to:

<ngx-editorjs [holder]="'editorjs'"></ngx-editorjs>

I get the 'I'm ready!' text from editor.js:2 appearing on the console but I am faced with the same error:

this.editorjs is not a constructor. 

Your dismissive behavior is incredibly condescending and your documentation is heinous. You give little to no examples you just send people to your 'working' example and hope that they comb through your entire project to figure out what exactly is going on. This is definitely a bug and should not be closed because I am not the only person facing this issue.

**Comment by CarlosValencia78** [comment]
Upon cloning your project it works, however when trying to implement your design (app.module.ts, app.component.html, package.json) I am faced with the error:

ERROR error: Uncaught (in promise): Error: Error in NgxEditorJSDirective::ngAfterContentInit - Directive element has no ID

When I apply the attribute [holder]="'editorjs'", I am met with the original 'this.editorjs is not a constructor' error. 

I would appreciate some help other than you sending me to your GitHub, it has not helped solve this issue in the two other bugs I have seen that are facing the same exact issue.

**Comment by tanepiper** [comment]
@CarlosValencia78 If you are passing a holder, you also need an element with that ID on the page (e.g. `<div id="editorjs"></div>`)

https://github.com/tanepiper/ngx-tinynodes/blob/master/libs/ngx-editorjs/ngx-editorjs/src/lib/directives/ngx-editorjs.directive.ts#L252
