### ISSUE TITLE
[BUG] ngx-editorjs: 2.1.0: Inline Link missing

### ISSUE THREAD

**Issue by xel-x** [tanepiper/ngx-tinynodes#6]
**Which Library?**
ngx-editorjs: 2.1.0

**Describe the bug**
Having read the code of editor.js it seems like bold, italic and link are baked into editor.js directly and there is not much I could do to add/remove one or the other. They also work perfectly on editorjs.io, but link seems to be missing when used with ngx-editorjs.

**To Reproduce**
1. goto [Demopage](https://tinynodes-ngx.firebaseapp.com/ngx-editorjs-demo/angular-component)
2. Add a Paragraph (with some text)
3. Select some text
4. See B and i within the floating toolbar, but not the link symbol/button.

**Expected behavior**
See the link symbol, being able to click it so I can add a link (or remove an existing link).
See by repoducing above steps on [editorjs.io](https://editorjs.io)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.4
 - Browser: Vivaldi (Chromium Rendering Engine)
 - Version: 2.5.1525.48

**One other thing**
I want to say thank you! The work you did here is really appreciated.

**Comment by tanepiper** [comment]
@xel-x Hi there, At the moment it's not included in the default plugin package.

Currently, I'm working on version 3 and with that a new plugin architecture, and with that, I will be including all the default EditorJS plugins.  This should be out later this week. At the moment it's only the block plugins and the marker plugin for now.

You can see the new plugin structure here: https://github.com/tanepiper/ngx-tinynodes/tree/features/better-plugins/libs/ngx-editorjs-plugins

I'll update the ticket once I've released

**Comment by tanepiper** [comment]
@xel-x Hi, update on the ticket - after some further research, it is indeed a bug! It seems the inline toolbar does not show. I'll investigate further

**Comment by tanepiper** [comment]
Hi @xel-x thanks again for the bug report, it's been fixed in the new version where the `inlineTool` property is now set on a plugins config, however, ~~in releasing it seems something else broke slightly so I need to check it out~~ it seems I've discovered a bug in the Header plugin from EditorJS that broke some other code

**Comment by xel-x** [comment]
Big thanks for the fix 👍 

I guess 3.0.0 needs angular 8?

Just asking because it still says it needs the peer dependencies in Version ~7.2.15 but throws errors on it, while working smoothly on angular 8.

**Comment by tanepiper** [comment]
@xel-x ahh thanks yes I forgot to update the peer deps. I'll fix that and do a quick release along with a couple of small fixes.

FYI there is also a know bug with the Header Plugin for now, I've raised a PR as the fix is on their end since Angular 8 - https://github.com/editor-js/header/pull/25

**Comment by tanepiper** [comment]
@xel-x Thanks again for your report - I've released 3.0.1 and plugins 2.0.1 that fixes the peer dependency issues, also some internal changes and a temporary fix for the Header issue.
